name: Build BiliM

on:
  workflow_dispatch:
    inputs:
      release:
        description: "yes to release"
        required: false

jobs:
  Build-BiliM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JRE
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "21"
          java-package: "jre"

      - name: Get BiliM Releases
        uses: robinraju/release-downloader@v1.11
        with:
          repository: "sakarie9/BiliRoamingM"
          latest: true
          fileName: "BiliRoamingM-*"

      - name: Rename BiliM
        run: |
          mv *-integrations-*.apk integrations.apk
          mv *-patches-*.jar patches.jar

      - name: Export BiliM LATEST_TAG
        run: |
          tag=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/sakarie9/BiliRoamingM/releases/latest" \
            | jq -r .tag_name)
          echo "BiliM_LATEST_TAG=${tag#v}" >> $GITHUB_ENV

      - name: Get Revanced CLI
        uses: robinraju/release-downloader@v1.11
        with:
          repository: "zjns/revanced-cli"
          latest: true
          fileName: "revanced-cli.jar"

      - name: Get Bilibili-Play
        run: |
          UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36"
          wget -q --user-agent="$UA" -O "play.apk" "https://d.apkpure.com/b/APK/com.bilibili.app.in?version=latest"

      # Check $version & $versionCode
      - name: "Get play Info"
        id: "apk-info-play"
        uses: "8Mi-Tech/get-apk-info-action@master"
        with:
          apkPath: "play.apk"
      # Get play $patchVersion $patchVersionCode
      - name: Get Bilibili-Play Info
        run: |
          echo "Bili_play_ver=${{steps.apk-info-play.outputs.versionNum}}" >> $GITHUB_ENV
          echo "Bili_play_vercode=${{steps.apk-info-play.outputs.versionCode}}" >> $GITHUB_ENV

      - name: Build BiliM-play
        run: |
          java -jar revanced-cli.jar patch --merge integrations.apk --patch-bundle patches.jar --signing-levels 1,2,3 play.apk

      # named Bilix-play
      - name: Rename Bilix-play
        run: |
          mv play-patched.apk BiliM-play-${Bili_play_ver}-${BiliM_LATEST_TAG}.apk
          echo "BiliM_play_patched_path=BiliM-play-${{ env.Bili_play_ver }}-${{ env.BiliM_LATEST_TAG }}.apk"  >> $GITHUB_ENV

      # Signing Bilix-play
      - name: Resign Bilix-play
        run: |
          cd ./
          echo Downloading uber-apk-signer
          wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar
          echo ${{ secrets.SIGNING_KEY }} > bilim.base64
          base64 -d bilim.base64 > bilim.jks
          java -jar uber-apk-signer-1.3.0.jar \
            -a ${{ env.BiliM_play_patched_path }} --overwrite --allowResign \
            --ks bilim.jks --ksAlias bili --ksKeyPass bilibili --ksPass bilibili

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bilim-${Bili_play_ver}-${BiliM_LATEST_TAG}
          path: ${{ env.BiliM_play_patched_path }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: inputs.release == 'yes'
        with:
          draft: true
          name: BiliM-play-${{ env.Bili_play_ver }}-${{ env.BiliM_LATEST_TAG }}
          body: v${Bili_play_ver}-${BiliM_LATEST_TAG}
          fail_on_unmatched_files: true
          files: |
            ${{ env.BiliM_play_patched_path }}

      - name: Upload files to Telegram
        uses: xz-dev/TelegramFileUploader@v1.1.1
        if: inputs.release == 'yes'
        with:
          to-who: ${{ secrets.TG_CHAT_ID }}
          message: "v${Bili_play_ver}-${BiliM_LATEST_TAG}\n[Github Releases](https://github.com/sakarie9/BiliRoamingM-PreBuilds/releases/tag/v${Bili_play_ver}-${BiliM_LATEST_TAG})"
          files: |
            ${{ env.BiliM_play_patched_path }}
        env:
          API_ID: 611335
          API_HASH: d524b414d21f4d37f08684c1df41ac9c
          BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
